Comment branch
Parkgeonmoo/Anonymous_Community pull request #2
Opened 2023-09-18 06:38 UTC by Parkgeonmoo

### 2023-09-18 PR 사항
- 댓글에 대한 GET,PUT,DELETE 로직 구현 
- 계층은 controller,service,dao 세 개로 나뉘어서 구현
- 통신을 할 때 controller는 dto 형태로 글/댓글을 받고 service 단계에서 해당 부분을 Entity로 변환하여 dao에 넘겨주며 받은 결과값을 다시 controller에 넘겨줄때는 dto 형태로 변환하여 넘겨주는 방식으로 구현

### PR 받았으면 하는 부분
- 방어 코드 및 try-catch를 진행하는데에 있어  dao와 service,controller 모든 부분에 처리를 해야하는지?
- 현재는 password가 담긴 부분이 있어 @RequestBody를 통해 필요없는 정보들도 포함하고 있는 dto 형태로 넘기는데 이렇게 구현하면 되는지?
- 현재는 restapi가 article/comment가 같이 묶여있는데 보통 양이 많아지게 되면 도메인별로 나누는 것이 좋은지?

2023-09-18 13:53 UTC, kimso0907 requested changes

2023-09-18 13:53 UTC, kimso0907 commented on src/main/java/com/example/anonymous_community/controller/RestApi.java
>  @Slf4j
미사용 어노테이션 제거해주세요

2023-09-18 13:53 UTC, kimso0907 commented on src/main/java/com/example/anonymous_community/controller/RestApi.java
>  import org.springframework.web.bind.annotation.*;
- 와일드카드(*) 사용해서 패키지 전체를 임포트 하지 말고 개별 임포트 사용하기
    - 사용하지 말아야 하는 이유 1. https://yanoo.tistory.com/152
    - 사용자지 말아야 하는 이유 2. https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=nine01223&logNo=220422659318
    - 참고 링크 첨부합니다

2023-09-18 13:53 UTC, kimso0907 commented on src/main/java/com/example/anonymous_community/controller/RestApi.java
> +    public RestApi(ArticleService articleservice, CommentService commentService) {
생성자 주입은 @RequiredArgsConstructor 를 사용하면 훨씬 가독성 있게 주입할 수 있습니다

2023-09-18 13:53 UTC, kimso0907 commented on src/main/java/com/example/anonymous_community/controller/RestApi.java
> +        }else{
- 프로젝트에 띄어쓰기 컨밴션을 만들어 주세요
- 보편적으로 띄어쓰기가 되는 부분 참고해 주세요
  - 닫는괄호 뒤
  - 쉼표 뒤
  - if, else, while, for 문 바로 뒤 등 …

2023-09-18 13:53 UTC, kimso0907 commented on src/main/java/com/example/anonymous_community/controller/RestApi.java
> +    public ResponseEntity putComment(@RequestBody Comment inputComment) {
Api 메소드 명은 doMethodAs… 형식으로 가져가면 직관적이고 깔끔합니다
Ex. putComment > doPutAsComment

2023-09-18 13:53 UTC, kimso0907 commented on src/main/java/com/example/anonymous_community/controller/RestApi.java
>      @GetMapping("/comment")
Api는 Restful하게 작성해 주세요
Ex. /api/comment?articleIndex={articleInex} > /api/article/{articleIndex}/comment

2023-09-18 13:53 UTC, kimso0907 commented on src/main/java/com/example/anonymous_community/controller/RestApi.java
>      @GetMapping("/comment")
위와 같이 설계하면 api 설계만 보고도 {articleIndex} 에 속한 코멘트를 조회하는 api 임을 알 수 있습니다

2023-09-18 13:53 UTC, kimso0907 commented on src/main/java/com/example/anonymous_community/controller/RestApi.java
> -public class restapi {
Api 를 도메인 단위로 분리해 주세요
Ex. ArticleController, CommentController

2023-09-18 13:53 UTC, kimso0907 commented on src/main/java/com/example/anonymous_community/controller/RestApi.java
> +        Article result = articleService.postArticleService(inputArticle);
한번 생성된 뒤 다시 할당되지 않는 데이터는 final로 선언해 주세요
- final 을 사용해야 하는 이유 참고해 주세요 >>>  https://mangkyu.tistory.com/131

2023-09-18 13:53 UTC, kimso0907 commented on src/main/java/com/example/anonymous_community/service/ArticleService.java
> +    public Article postArticleService(Article inputArticle) {
클래스에 article, service가 명시되어 있는데 메소드 명에 article과 service를 중복해서 붙일 필요가 없습니다. 데이터를 생성 하는 메소드의 경우 entry 로 이름을 지어 주세요. 서비스의 경우에도 목적에 맞게 분리해 주면 가독성과 유지보수의 효율성이 올라갑니다.
Ex. ArticleService.postArticleService > ArticleEntryService.entry

2023-09-18 13:53 UTC, kimso0907 commented on src/main/java/com/example/anonymous_community/service/ArticleService.java
>              if (inputArticle != null) {
예외 처리의 경우 early-return 을 사용하면 가독성이 올라가고 이런 경우에는 try-catch 사용의 리소스를 줄일 수 있습니다
- early-return 참고 : https://jheloper.github.io/2019/06/write-early-return-code/
- try-caatch 리소스 참고 : https://moonsiri.tistory.com/174
- 코드 수정은 아래와 같이 할 수 있습니다
- `if (inputAtricle == null) {
    throw new IllegalArgumentException(“입력하신 글의 내용이 비어 있습니다.”); // 최종적으로는 예외 케이스도 별도로 관리가 필요합니다. To be continue …
}`

2023-09-18 13:53 UTC, kimso0907 commented on src/main/java/com/example/anonymous_community/dao/CommentDao.java
> +                System.out.println("해당하는 댓글이 존재하지 않습니다.");
로그를 남길 때는 로그백을 사용해 주세요
- System.out.println 를 사용하지 말아야 하는 이유 > https://hudi.blog/do-not-use-system-out-println-for-logging/

2023-09-18 13:53 UTC, kimso0907 commented on src/main/java/com/example/anonymous_community/dto/Comment.java
>      private String articleIndex;
created_Time, updated_Time 변수 카멜 케이스로 변경해 주세요. 스네이크 케이스 이면서 첫 번째 스펠링이 대문자인 케이스는 존재하지 않습니다.

2023-09-18 13:53 UTC, kimso0907 commented on src/main/java/com/example/anonymous_community/service/ArticleService.java
>          articleEntity articleEntity = new articleEntity();
데이터를 insert 할 때 Entity의 데이터를 setter 로 채우는 것 보다 Article 객체를 생성자의 매개변수로 전달한 뒤 Entity 의 생성자에서 데이터를 set 하면 코드를 훨씬 간결하게 작성할 수 있습니다. 또, 시간의 경우 데이터의 속성이기 때문에 서비스가 아닌 entity 내부에서 컨트롤 하는것이 더 적절합니다.

2023-09-19 05:00 UTC, Parkgeonmoo commented on src/main/java/com/example/anonymous_community/service/ArticleService.java
> +    public Article postArticleService(Article inputArticle) {
메소드 명 변경에 대한 팁은 리뷰를 통해 수정 필요

2023-09-19 22:05 UTC, kimso0907 commented on src/main/java/com/example/anonymous_community/controller/ArticleController.java
> +        Article result = articleEntryService.getArticleService(articleindex);
이후 작업에서는 final 선언에 대한 고려도 해주세요

2023-09-19 22:12 UTC, kimso0907 commented
createdTime, updatedTime 은 현재 구현한 것 처럼 entity 레벨에서 작업해 주면 유용합니다. 테이블이 많아지고 created_time, updated_time 컬럼이 늘어나면 해당 두 컬럼은 분리하여 상속받는것도 고려할 수 있습니다.

2023-09-19 22:18 UTC, kimso0907 commented on src/main/java/com/example/anonymous_community/service/CommentEntryService.java
> +    public Comment postCommentService(Comment inputComment) {
클래스를 목적 별로 분리하고 메소드 명도 목적에 맞게 변경하면 가독성이 올라가고 유지보수에 유리합니다.
ex.
CommentEntryService.entry > 코멘트 작성
CommentUpdateService.update > 코멘트 수정
CommentOneService.getOne > 단건 조회
CommentListService.getList > 목록 조회

2023-09-19 22:18 UTC, kimso0907 commented on src/main/java/com/example/anonymous_community/service/ArticleEntryService.java
> +        if (password == null || !password.matches("^[a-zA-Z0-9]{6,10}$")) {
String관련 메서드는 apache common lang3 의 StringUtils를 이용하면 좋습니다. StringUtils.isBlank(password) 로 확인하면 null 인지를 확인하면서 password 가 빈 문자열인지도 확인 가능합니다.

2023-10-03 08:35 UTC, Parkgeonmoo commented
@kimso0907  
-서비스 계층 클래스가 각각 하나의 역할만을 하도록 분리 
-private final로 모든 객체 변경
-jpa를 통해서 불필요한 중복 save 로직 제거
-@Entity의 코드 통일성을 위한 코드 제거

2023-10-03 08:37 UTC, kimso0907 commented on src/main/java/com/example/anonymous_community/dao/ArticleDao.java
> +public class ArticleDao {
추후 dao 역할에 따른 분리도 고려해주세요

2023-10-03 08:42 UTC, kimso0907 approved these changes

2023-10-03 08:43 UTC, merged